name: Run Script When Source Files Change

on:
  push:
    paths:
      - 'source/**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Python script
        env:
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python scripts/handle_changed_files.py

      - name: Commit updated reports to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add reports/

          # Only commit if there are actual changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: add updated reports [skip ci]"
            git push
          else
            echo "No report changes to commit."
          
          fi
